@extends('layouts.app')
@section('title', 'Data Magang')
@section('content')
<div class="space-y-6">
    <div><p class="text-sm font-medium text-slate-500">Manajemen Magang</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-slate-950">Data Magang</h1><p class="mt-1 text-sm text-slate-500">Kelola mahasiswa yang telah memiliki pengajuan magang yang disetujui.</p></div>
    <div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" action="{{ route('admin.magang.index') }}" class="flex flex-col gap-3 lg:flex-row">
        <input name="q" value="{{ $search }}" type="search" placeholder="Cari mahasiswa, NIM, judul, dosen, atau instansi..." class="min-w-0 flex-1 rounded-lg border border-slate-300 px-4 py-2.5 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200">
        <select name="status" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm text-slate-700"><option value="">Semua Status</option><option value="belum_mulai" @selected($status==='belum_mulai')>Belum Mulai</option><option value="berlangsung" @selected($status==='berlangsung')>Berlangsung</option><option value="selesai" @selected($status==='selesai')>Selesai</option></select>
        <select name="per_page" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm text-slate-700">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected($perPage===$size)>{{ $size }} / halaman</option>@endforeach</select>
        <button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Filter</button><button name="export" value="excel" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700"><i class="fa-solid fa-file-excel mr-2"></i>Export Excel</button>
        @if($search||$status)<a href="{{ route('admin.magang.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold text-slate-700">Reset</a>@endif
        <input type="hidden" name="sort" value="{{ $sort }}"><input type="hidden" name="direction" value="{{ $direction }}">
    </form></div>
    <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead><tr>
        <th class="px-5 py-3 text-left"><x-table-sort column="mahasiswa" label="Mahasiswa" /></th><th class="px-5 py-3 text-left"><x-table-sort column="judul_magang" label="Judul Magang" /></th><th class="px-5 py-3 text-left"><x-table-sort column="dosen" label="Dosen Pembimbing" /></th><th class="px-5 py-3 text-left"><x-table-sort column="instansi" label="Instansi" /></th><th class="px-5 py-3 text-left"><x-table-sort column="status_magang" label="Status Magang" /></th><th class="px-5 py-3 text-left font-semibold text-white">Aksi</th>
    </tr></thead><tbody class="divide-y divide-slate-100">
    @forelse($magang as $item)
        @php $statusClass=match($item->status_magang){'berlangsung'=>'bg-sky-50 text-sky-700','selesai'=>'bg-emerald-50 text-emerald-700',default=>'bg-amber-50 text-amber-700'}; $statusLabel=match($item->status_magang){'belum_mulai'=>'Belum Mulai','berlangsung'=>'Berlangsung','selesai'=>'Selesai',default=>ucfirst($item->status_magang)}; @endphp
        <tr class="hover:bg-slate-50"><td class="px-5 py-4"><div class="font-semibold text-slate-900">{{ $item->mahasiswa?->nama ?? '-' }}</div><div class="text-xs text-slate-500">{{ $item->mahasiswa?->nim ?? '-' }}</div></td><td class="max-w-xs px-5 py-4 text-slate-700">{{ $item->judul_magang ?: '-' }}</td><td class="px-5 py-4 text-slate-600">{{ $item->dosen?->nama ?? '-' }}</td><td class="px-5 py-4 text-slate-600">{{ $item->instansi?->nama_instansi ?? '-' }}</td><td class="px-5 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold {{ $statusClass }}">{{ $statusLabel }}</span></td><td class="whitespace-nowrap px-5 py-4"><a href="{{ route('admin.magang.show',$item) }}" class="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700">Detail</a></td></tr>
    @empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-slate-500">Belum ada data magang yang disetujui.</td></tr>@endforelse
    </tbody></table></div><div class="flex flex-col gap-3 border-t border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-slate-500">Menampilkan {{ $magang->firstItem() ?? 0 }}–{{ $magang->lastItem() ?? 0 }} dari {{ $magang->total() }} data</p>{{ $magang->onEachSide(1)->links() }}</div></div>
</div>
@endsection