@extends('layouts.app')
@section('title','Laporan Magang')
@section('content')
<div class="space-y-6">
    <div><h1 class="text-2xl font-bold tracking-tight text-slate-950">Laporan Magang</h1><p class="mt-1 text-sm text-slate-500">Tinjau dan validasi laporan mahasiswa bimbingan.</p></div>
    <div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" action="{{ route('dosen.laporan') }}" class="flex flex-col gap-3 lg:flex-row">
        <input name="q" value="{{ $search }}" type="search" placeholder="Cari mahasiswa, NIM, perusahaan, atau file..." class="min-w-0 flex-1 rounded-lg border border-slate-300 px-4 py-2.5 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200">
        <select name="status" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Semua Status</option><option value="belum_validasi" @selected($status==='belum_validasi')>Belum Validasi</option><option value="disetujui" @selected($status==='disetujui')>Disetujui</option><option value="ditolak" @selected($status==='ditolak')>Ditolak</option></select>
        <select name="per_page" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected($perPage===$size)>{{ $size }} / halaman</option>@endforeach</select>
        <button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Filter</button><button name="export" value="excel" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700"><i class="fa-solid fa-file-excel mr-2"></i>Export Excel</button>
        @if($search || $status)<a href="{{ route('dosen.laporan') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold text-slate-700">Reset</a>@endif
        <input type="hidden" name="sort" value="{{ $sort }}"><input type="hidden" name="direction" value="{{ $direction }}">
    </form></div>
    <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead><tr>
        <th class="px-5 py-3 text-left"><x-table-sort column="mahasiswa" label="Mahasiswa" /></th><th class="px-5 py-3 text-left"><x-table-sort column="perusahaan" label="Perusahaan" /></th><th class="px-5 py-3 text-left"><x-table-sort column="file" label="File" /></th><th class="px-5 py-3 text-left"><x-table-sort column="tanggal_upload" label="Upload" /></th><th class="px-5 py-3 text-left"><x-table-sort column="status" label="Status" /></th><th class="px-5 py-3 text-left">Aksi</th>
    </tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($laporan as $item)
            <tr class="align-top hover:bg-slate-50"><td class="px-5 py-4"><b>{{ $item->magang?->mahasiswa?->nama }}</b><div class="text-xs text-slate-500">{{ $item->magang?->mahasiswa?->nim }}</div></td><td class="px-5 py-4">{{ $item->magang?->instansi?->nama_instansi }}</td><td class="px-5 py-4"><a class="font-semibold text-slate-700 underline" href="{{ route('dosen.laporan.download',$item) }}">{{ $item->nama_file }}</a></td><td class="px-5 py-4 whitespace-nowrap">{{ $item->tanggal_upload?->format('d M Y H:i') }}</td><td class="px-5 py-4"><x-badge :status="$item->status"/></td><td class="min-w-[240px] px-5 py-4">@if($item->status==='belum_validasi')<form method="POST" action="{{ route('dosen.laporan.validate',$item) }}" class="space-y-2">@csrf @method('PATCH')<select name="status" class="w-full rounded-lg border border-slate-300 p-2 text-sm" required><option value="">Pilih keputusan</option><option value="disetujui">Setujui</option><option value="ditolak">Tolak</option></select><textarea name="catatan_dosen" rows="2" placeholder="Catatan, wajib jika ditolak" class="w-full rounded-lg border border-slate-300 p-2 text-sm"></textarea><button class="w-full rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Simpan</button></form>@else<p class="text-xs text-slate-500">{{ $item->catatan_dosen ?: 'Tidak ada catatan.' }}</p>@endif</td></tr>
        @empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-slate-500">Belum ada laporan.</td></tr>@endforelse
    </tbody></table></div><div class="flex flex-col gap-3 border-t border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-slate-500">Menampilkan {{ $laporan->firstItem() ?? 0 }}–{{ $laporan->lastItem() ?? 0 }} dari {{ $laporan->total() }} data</p>{{ $laporan->onEachSide(1)->links() }}</div></div>
</div>
@endsection
