@extends('layouts.app')
@section('title','Mahasiswa Bimbingan')
@section('content')
<div class="space-y-6">
<div><h1 class="text-2xl font-bold">Mahasiswa Bimbingan</h1><p class="mt-1 text-sm text-slate-500">Daftar mahasiswa yang berada dalam bimbingan Anda.</p></div>
<form class="flex flex-col gap-3 rounded-xl border bg-white p-4 shadow-sm sm:flex-row"><input name="q" value="{{ $search }}" placeholder="Cari nama atau NIM..." class="flex-1 rounded-lg border p-2.5 text-sm"><select name="status" class="rounded-lg border p-2.5 text-sm"><option value="">Semua status</option><option value="belum_mulai" @selected($status==='belum_mulai')>Belum Mulai</option><option value="berlangsung" @selected($status==='berlangsung')>Berlangsung</option><option value="selesai" @selected($status==='selesai')>Selesai</option></select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form>
<div class="overflow-x-auto rounded-xl border bg-white shadow-sm"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">Mahasiswa</th><th class="p-4 text-left">Perusahaan</th><th class="p-4 text-left">Periode</th><th class="p-4 text-left">Status</th><th class="p-4 text-left">Logbook</th><th class="p-4"></th></tr></thead><tbody class="divide-y">@forelse($magang as $item)<tr><td class="p-4"><b>{{ $item->mahasiswa?->nama }}</b><div class="text-xs text-slate-500">{{ $item->mahasiswa?->nim }}</div></td><td class="p-4">{{ $item->instansi?->nama_instansi }}</td><td class="p-4">{{ $item->tanggal_mulai?->format('d M Y') ?? '-' }} — {{ $item->tanggal_selesai?->format('d M Y') ?? '-' }}</td><td class="p-4"><x-badge :status="$item->status_magang"/></td><td class="p-4">{{ $item->logbook_disetujui_count }}/{{ $item->log_kegiatan_count }} disetujui</td><td class="p-4"><a href="{{ route('dosen.mahasiswa-bimbingan.show',$item) }}" class="font-semibold underline">Detail</a></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-500">Belum ada mahasiswa bimbingan.</td></tr>@endforelse</tbody></table></div>
@if($magang->hasPages())<div>{{ $magang->links() }}</div>@endif
</div>
@endsection