@extends('layouts.app')
@section('title','Laporan Magang')
@section('content')
<div class="space-y-6">
    <div><h1 class="text-2xl font-bold">Laporan Magang</h1><p class="mt-1 text-sm text-slate-500">Upload laporan akhir dan pantau validasi dosen.</p></div>
    @if(!$magang)
        <div class="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Belum ada magang yang disetujui. Laporan tersedia setelah pengajuan disetujui.</div>
    @else
        <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid gap-4 sm:grid-cols-3"><div><p class="text-xs text-slate-500">Judul</p><p class="font-semibold">{{ $magang->judul_magang }}</p></div><div><p class="text-xs text-slate-500">Perusahaan</p><p class="font-semibold">{{ $magang->instansi?->nama_instansi }}</p></div><div><p class="text-xs text-slate-500">Status Magang</p><x-badge :status="$magang->status_magang"/></div></div></div>
        @if($canUpload)<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-bold">Upload Laporan</h2><form method="POST" action="{{ route('mahasiswa.laporan.store') }}" enctype="multipart/form-data" class="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end">@csrf<div class="flex-1"><label class="text-sm font-semibold">File PDF</label><input type="file" name="file" accept=".pdf,application/pdf" required class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><p class="mt-1 text-xs text-slate-500">PDF maksimal 5 MB.</p>@error('file')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><button class="rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Upload</button></form></div>@endif
        <div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" action="{{ route('mahasiswa.laporan') }}" class="flex flex-col gap-3 lg:flex-row"><input name="q" value="{{ $search }}" placeholder="Cari nama file atau catatan..." class="min-w-0 flex-1 rounded-lg border border-slate-300 px-4 py-2.5 text-sm"><select name="status" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Semua Status</option><option value="belum_validasi" @selected($status==='belum_validasi')>Belum Validasi</option><option value="disetujui" @selected($status==='disetujui')>Disetujui</option><option value="ditolak" @selected($status==='ditolak')>Ditolak</option></select><select name="per_page" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected($perPage===$size)>{{ $size }} / halaman</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Filter</button><button name="export" value="excel" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700"><i class="fa-solid fa-file-excel mr-2"></i>Export Excel</button>@if($search || $status)<a href="{{ route('mahasiswa.laporan') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold text-slate-700">Reset</a>@endif<input type="hidden" name="sort" value="{{ $sort }}"><input type="hidden" name="direction" value="{{ $direction }}"></form></div>
        <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead><tr><th class="px-5 py-3 text-left"><x-table-sort column="nama_file" label="File" /></th><th class="px-5 py-3 text-left"><x-table-sort column="tanggal_upload" label="Tanggal" /></th><th class="px-5 py-3 text-left"><x-table-sort column="status" label="Status" /></th><th class="px-5 py-3 text-left">Catatan</th><th class="px-5 py-3 text-left">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($laporan as $item)<tr class="hover:bg-slate-50"><td class="px-5 py-4 font-semibold">{{ $item->nama_file }}</td><td class="px-5 py-4 whitespace-nowrap">{{ $item->tanggal_upload?->format('d M Y H:i') ?? '-' }}</td><td class="px-5 py-4"><x-badge :status="$item->status"/></td><td class="px-5 py-4 text-slate-600">{{ $item->catatan_dosen ?: '-' }}</td><td class="px-5 py-4"><div class="flex gap-3"><a href="{{ route('mahasiswa.laporan.download',$item) }}" class="text-xs font-semibold underline">Download</a>@if($item->status==='belum_validasi')<form method="POST" action="{{ route('mahasiswa.laporan.destroy',$item) }}" onsubmit="return confirm('Hapus laporan ini?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600">Hapus</button></form>@endif</div></td></tr>
            @empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Belum ada laporan.</td></tr>@endforelse
        </tbody></table></div><div class="flex flex-col gap-3 border-t border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-slate-500">Menampilkan {{ $laporan->firstItem() ?? 0 }}–{{ $laporan->lastItem() ?? 0 }} dari {{ $laporan->total() ?? 0 }} data</p>@if(method_exists($laporan,'hasPages')){{ $laporan->onEachSide(1)->links() }}@endif</div></div>
    @endif
</div>
@endsection
