@extends('layouts.app')
@section('title','Laporan Magang')
@section('content')
<div class="space-y-6"><div><h1 class="text-2xl font-bold">Laporan Magang</h1><p class="mt-1 text-sm text-slate-500">Upload laporan akhir dan pantau validasi dosen.</p></div>
@if(!$magang)<div class="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Belum ada magang yang disetujui. Laporan tersedia setelah pengajuan disetujui.</div>@else
<div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid gap-4 sm:grid-cols-3"><div><p class="text-xs text-slate-500">Judul</p><p class="font-semibold">{{ $magang->judul_magang }}</p></div><div><p class="text-xs text-slate-500">Perusahaan</p><p class="font-semibold">{{ $magang->instansi?->nama_instansi }}</p></div><div><p class="text-xs text-slate-500">Status Magang</p><x-badge :status="$magang->status_magang"/></div></div></div>
@if($canUpload)<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-bold">Upload Laporan</h2><form method="POST" action="{{ route('mahasiswa.laporan.store') }}" enctype="multipart/form-data" class="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end">@csrf<div class="flex-1"><label class="text-sm font-semibold">File PDF</label><input type="file" name="file" accept=".pdf,application/pdf" required class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><p class="mt-1 text-xs text-slate-500">PDF maksimal 5 MB.</p>@error('file')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><button class="rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Upload</button></form></div>@endif
<div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left">File</th><th class="px-5 py-3 text-left">Tanggal</th><th class="px-5 py-3 text-left">Status</th><th class="px-5 py-3 text-left">Catatan</th><th class="px-5 py-3 text-left">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($laporan as $item)<tr><td class="px-5 py-4 font-semibold">{{ $item->nama_file }}</td><td class="px-5 py-4">{{ $item->tanggal_upload?->format('d M Y H:i') ?? '-' }}</td><td class="px-5 py-4"><x-badge :status="$item->status"/></td><td class="px-5 py-4 text-slate-600">{{ $item->catatan_dosen ?: '-' }}</td><td class="px-5 py-4"><div class="flex gap-3"><a href="{{ route('mahasiswa.laporan.download',$item) }}" class="text-xs font-semibold underline">Download</a>@if($item->status==='belum_validasi')<form method="POST" action="{{ route('mahasiswa.laporan.destroy',$item) }}" onsubmit="return confirm('Hapus laporan ini?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600">Hapus</button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Belum ada laporan.</td></tr>@endforelse</tbody></table></div></div>
@endif</div>
@endsection