@extends('layouts.app')
@section('title', 'Laporan')
@section('content')
<div class="space-y-6">
    <div><p class="text-sm font-medium text-slate-500">Dokumen Magang</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-slate-950">Laporan Magang</h1><p class="mt-1 text-sm text-slate-500">Lihat laporan mahasiswa yang telah dikirim dan pantau status validasinya.</p></div>
    <div class="grid gap-4 sm:grid-cols-3">
        @php $counts=\App\Models\Laporan::query()->whereHas('magang',fn($query)=>$query->where('status_pengajuan','disetujui'))->selectRaw("status, COUNT(*) as total")->groupBy('status')->pluck('total','status'); @endphp
        <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Belum Validasi</p><p class="mt-1 text-2xl font-bold text-amber-600">{{ $counts['belum_validasi'] ?? 0 }}</p></div>
        <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Disetujui</p><p class="mt-1 text-2xl font-bold text-emerald-600">{{ $counts['disetujui'] ?? 0 }}</p></div>
        <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Ditolak</p><p class="mt-1 text-2xl font-bold text-rose-600">{{ $counts['ditolak'] ?? 0 }}</p></div>
    </div>
    <div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" action="{{ route('admin.laporan.index') }}" class="flex flex-col gap-3 lg:flex-row">
        <input name="q" value="{{ $search }}" type="search" placeholder="Cari nama file, mahasiswa, NIM, dosen, atau perusahaan..." class="min-w-0 flex-1 rounded-lg border border-slate-300 px-4 py-2.5 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200">
        <select name="status" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm text-slate-700"><option value="">Semua Status</option><option value="belum_validasi" @selected($status==='belum_validasi')>Belum Validasi</option><option value="disetujui" @selected($status==='disetujui')>Disetujui</option><option value="ditolak" @selected($status==='ditolak')>Ditolak</option></select>
        <select name="per_page" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm text-slate-700">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected($perPage===$size)>{{ $size }} / halaman</option>@endforeach</select>
        <button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Filter</button><button name="export" value="excel" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700"><i class="fa-solid fa-file-excel mr-2"></i>Export Excel</button>
        @if($search||$status)<a href="{{ route('admin.laporan.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold text-slate-700">Reset</a>@endif
        <input type="hidden" name="sort" value="{{ $sort }}"><input type="hidden" name="direction" value="{{ $direction }}">
    </form></div>
    <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[1050px] w-full divide-y divide-slate-200 text-sm"><thead><tr>
        <th class="px-5 py-3 text-left"><x-table-sort column="mahasiswa" label="Mahasiswa" /></th><th class="px-5 py-3 text-left"><x-table-sort column="perusahaan" label="Perusahaan" /></th><th class="px-5 py-3 text-left"><x-table-sort column="dosen" label="Dosen Pembimbing" /></th><th class="px-5 py-3 text-left"><x-table-sort column="nama_file" label="File Laporan" /></th><th class="px-5 py-3 text-left"><x-table-sort column="tanggal_upload" label="Tanggal Upload" /></th><th class="px-5 py-3 text-left"><x-table-sort column="status" label="Status" /></th><th class="px-5 py-3 text-left font-semibold text-white">Aksi</th>
    </tr></thead><tbody class="divide-y divide-slate-100">
    @forelse($laporan as $item)
        @php $statusClass=match($item->status){'disetujui'=>'bg-emerald-50 text-emerald-700','ditolak'=>'bg-rose-50 text-rose-700',default=>'bg-amber-50 text-amber-700'}; $statusLabel=match($item->status){'disetujui'=>'Disetujui','ditolak'=>'Ditolak',default=>'Belum Validasi'}; @endphp
        <tr class="hover:bg-slate-50"><td class="px-5 py-4"><div class="font-semibold text-slate-900">{{ $item->magang?->mahasiswa?->nama ?? '-' }}</div><div class="text-xs text-slate-500">{{ $item->magang?->mahasiswa?->nim ?? '-' }}</div></td><td class="px-5 py-4 text-slate-700">{{ $item->magang?->instansi?->nama_instansi ?? '-' }}</td><td class="px-5 py-4 text-slate-700">{{ $item->magang?->dosen?->nama ?? '-' }}</td><td class="px-5 py-4"><div class="max-w-xs truncate font-medium text-slate-800">{{ $item->nama_file }}</div></td><td class="whitespace-nowrap px-5 py-4 text-slate-600">{{ $item->tanggal_upload?->format('d M Y H:i') ?? '-' }}</td><td class="px-5 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold {{ $statusClass }}">{{ $statusLabel }}</span>@if($item->catatan_dosen)<p class="mt-1 max-w-xs text-xs text-slate-500">{{ $item->catatan_dosen }}</p>@endif</td><td class="whitespace-nowrap px-5 py-4"><a href="{{ route('admin.laporan.download',$item) }}" class="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700">Unduh</a></td></tr>
    @empty<tr><td colspan="7" class="px-5 py-12 text-center text-sm text-slate-500">Belum ada laporan magang yang dikirim.</td></tr>@endforelse
    </tbody></table></div><div class="flex flex-col gap-3 border-t border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-slate-500">Menampilkan {{ $laporan->firstItem() ?? 0 }}–{{ $laporan->lastItem() ?? 0 }} dari {{ $laporan->total() }} data</p>{{ $laporan->onEachSide(1)->links() }}</div></div>
</div>
@endsection