@extends('layouts.app')
@section('title','Ajukan Magang')
@section('content')
<div class="mx-auto max-w-3xl space-y-6"><div><h1 class="text-2xl font-bold">Ajukan Magang</h1><p class="mt-1 text-sm text-slate-500">Isi data pengajuan. Admin akan melakukan verifikasi dan persetujuan.</p></div>
<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><form method="POST" action="{{ route('mahasiswa.pengajuan.store') }}" class="space-y-5">@csrf
<div><label class="text-sm font-semibold">Tempat Magang <span class="text-rose-500">*</span></label><select name="instansi_id" required class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Pilih instansi</option>@foreach($instansi as $item)<option value="{{ $item->id }}" @selected(old('instansi_id',$selectedInstansi)==$item->id)>{{ $item->nama_instansi }} — {{ $item->alamat }}</option>@endforeach</select>@error('instansi_id')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-semibold">Dosen Pembimbing</label><select name="dosen_id" class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Belum ditentukan</option>@foreach($dosen as $item)<option value="{{ $item->id }}" @selected(old('dosen_id')==$item->id)>{{ $item->nama }} ({{ $item->nidn }})</option>@endforeach</select></div>
<div><label class="text-sm font-semibold">Judul Magang <span class="text-rose-500">*</span></label><input name="judul_magang" value="{{ old('judul_magang') }}" required class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error('judul_magang')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-semibold">Rencana Mulai</label><input type="date" name="tanggal_mulai" value="{{ old('tanggal_mulai') }}" class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error('tanggal_mulai')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-semibold">Rencana Selesai</label><input type="date" name="tanggal_selesai" value="{{ old('tanggal_selesai') }}" class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error('tanggal_selesai')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div></div>
<div><label class="text-sm font-semibold">Keterangan</label><textarea name="keterangan" rows="5" class="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">{{ old('keterangan') }}</textarea></div>
<div class="flex justify-end gap-3 border-t border-slate-200 pt-5"><a href="{{ route('mahasiswa.pengajuan') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold">Batal</a><button class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Kirim Pengajuan</button></div>
</form></div></div>
@endsection